In [1]:
import numpy as np

In [2]:
X =  np.array(([3,5], [5,1], [10,2]), dtype=float)
y = np.array(([75],[82], [93]), dtype=float)

In [4]:
X


array([[ 3.,  5.],
       [ 5.,  1.],
       [10.,  2.]])

In [5]:
y

array([[75.],
       [82.],
       [93.]])

In [6]:
X = X/np.amax(X, axis=0)
y = y/100

In [38]:
print (X.shape, y.shape)


(3, 2) (3, 1)


In [57]:
class Neural_Network(object):
    def __init__(self):
        #Define HyperParameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weight params
        self.W1 = np.random.randn(self.inputLayerSize,\
                                  self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,\
                                  self.outputLayerSize)
            
        
        
    def forward(self, X):
        #Propagate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        


    def sigmoid(self, z):
        #Apply the activation function
        return 1/(1+np.exp(-z))


In [58]:
NN = Neural_Network()

In [59]:
NN.forward(X)

array([[0.76376488],
       [0.72766632],
       [0.70768858]])

In [56]:
sigmoid(np.array([-1,0,1]))

array([0.26894142, 0.5       , 0.73105858])

In [42]:
sigmoid(np.random.randn(3,3))

array([[0.3694388 , 0.35655903, 0.29916004],
       [0.84178838, 0.75760151, 0.77396834],
       [0.66571409, 0.4656398 , 0.53261022]])